---
- name: Installiere nginx auf der hostgruppe "web"
  hosts: all
  become: yes # Play als admin ausführen
  tasks: 

    - name: Install nginx on machine
      dnf: 
        name: nginx
        state: present
      when: "'web' in group_names"
    
    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
      when: "'web' in group_names"

    - name: Install MariaDB on db hosts 
      dnf: 
        name: mariadb105
        state: present 
      when: "'db' in group_names"
    
    - name: Deploy custom web content
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      when: "'web' in group_names"
