- name: Überprüfe ob Nginx läuft
  hosts: hosts
  become: true
  tasks:
    - name: Überprüfe ob Nginx läuft
      shell: systemctl is-active nginx
      register: nginx_status
      ignore_errors: true

    - name: Neustarten von Nginx, falls er gestoppt ist
      service:
        name: nginx
        state: restarted
      when: "'inactive' in nginx_status.stdout or 'failed' in nginx_status.stdout"

    - name: Falls Nginx gestoppt ist, schreibe Log und starte neu
      lineinfile:
        path: /var/log/nginx_monitor.log
        line: "{{ ansible_date_time.iso8601 }} - Nginx wurde gestoppt und neu gestartet!"
        create: yes
        mode: '0644'
      when: "'inactive' in nginx_status.stdout or 'failed' in nginx_status.stdout"
